/* Notch filter to remove very annoying 5 kHz noise
 * emitted by the Hologram Nova modem board and
 * picked up by the Internet of Chuffs microphone,
 * This code based on C code generated by the wonderful http://t-filter.appspot.com 
 */

package main

/*

FIR filter designed with
http://t-filter.appspot.com

sampling frequency: 16000 Hz

* 0 Hz - 4000 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.6396776576733503 dB

* 4500 Hz - 5500 Hz
  gain = 0
  desired attenuation = -40 dB
  actual attenuation = -41.154584298451155 dB

* 6000 Hz - 8000 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.6396776576733503 dB

*/

//--------------------------------------------------------------------
// Types
//--------------------------------------------------------------------

const DESQUEAL_FIR_TAP_NUM int = 37

type DeSquealFir struct {
  History    [DESQUEAL_FIR_TAP_NUM]float32
  LastIndex  int
}

//--------------------------------------------------------------------
// Constants
//--------------------------------------------------------------------

//--------------------------------------------------------------------
// Variables
//--------------------------------------------------------------------

var deSquealFilterTaps = [...]float32{0.041812361726346135,
                                      0.050408268184899394,
                                      0.02714316553873565,
                                      0.0032687237329760603,
                                      -0.0584546458413332,
                                      0.058254709276715784,
                                      -0.011018465905755687,
                                      -0.0145503953670677,
                                      0.0001747265375015947,
                                      -0.0024277607343560484,
                                      0.0370532317538546,
                                      -0.024547590158464135,
                                      -0.06808921108657066,
                                      0.11574323540605948,
                                      -0.0007940277997022914,
                                      -0.1610320442154484,
                                      0.1361827297061767,
                                      0.07813477595892696,
                                      0.7919802707414938,
                                      0.07813477595892696,
                                      0.1361827297061767,
                                      -0.1610320442154484,
                                      -0.0007940277997022914,
                                      0.11574323540605948,
                                      -0.06808921108657066,
                                      -0.024547590158464135,
                                      0.0370532317538546,
                                      -0.0024277607343560484,
                                      0.0001747265375015947,
                                      -0.0145503953670677,
                                      -0.011018465905755687,
                                      0.058254709276715784,
                                      -0.0584546458413332,
                                      0.0032687237329760603,
                                      0.02714316553873565,
                                      0.050408268184899394,
                                      0.041812361726346135}

//--------------------------------------------------------------------
// Functions
//--------------------------------------------------------------------

func DeSquealFirInit(f* DeSquealFir) {
    for i := 0; i < len(deSquealFilterTaps); i++ {
        f.History[i] = 0
    }

    f.LastIndex = 0
}

func DeSquealFirPut(f* DeSquealFir, input float32) {
    f.History[f.LastIndex] = input
    f.LastIndex++
    if f.LastIndex == len(deSquealFilterTaps) {
        f.LastIndex = 0
    }
}

func DeSquealFirGet(f* DeSquealFir) float32 {
    var acc float32 = 0
    var index int = f.LastIndex

    for i := 0; i < len(deSquealFilterTaps); i++ {
        if index != 0 {
            index = index - 1
        } else {
            index = len(deSquealFilterTaps) - 1
        }
       acc += f.History[index] * deSquealFilterTaps[i]
    }

  return acc
}

/* End Of File */
