/* Notch filter to remove very annoying 5 kHz noise
 * emitted by the Hologram Nova modem board and
 * picked up by the Internet of Chuffs microphone,
 * This code based on C code generated by the wonderful http://t-filter.appspot.com 
 */

package main

/*

FIR filter designed with
http://t-filter.appspot.com

sampling frequency: 16000 Hz

* 0 Hz - 4000 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.9181592914724046 dB

* 4500 Hz - 5500 Hz
  gain = 0
  desired attenuation = -20 dB
  actual attenuation = -20.53395613206877 dB

* 6000 Hz - 8000 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.9181592914724046 dB

*/

//--------------------------------------------------------------------
// Types
//--------------------------------------------------------------------

const DESQUEAL_FIR_TAP_NUM int = 31

type DeSquealFir struct {
  History    [DESQUEAL_FIR_TAP_NUM]float32
  LastIndex  int
}

//--------------------------------------------------------------------
// Constants
//--------------------------------------------------------------------

//--------------------------------------------------------------------
// Variables
//--------------------------------------------------------------------

var deSquealFilterTaps = [...]float32{-0.11442365705990722,
                                      -0.016652959083222105,
                                      0.02737677703091019,
                                      0.020480690262803695,
                                      -0.015248941295772145,
                                      -0.019866078767932702,
                                      0.015303797257242607,
                                      0.04627482337091298,
                                      -0.03240289292886104,
                                      -0.04287924865801442,
                                      0.09863225194567758,
                                      -0.010347186414305518,
                                      -0.12898930627393007,
                                      0.11943980998550839,
                                      0.12025913888857047,
                                      0.7344043043041362,
                                      0.12025913888857047,
                                      0.11943980998550839,
                                      -0.12898930627393007,
                                      -0.010347186414305518,
                                      0.09863225194567758,
                                      -0.04287924865801442,
                                      -0.03240289292886104,
                                      0.04627482337091298,
                                      0.015303797257242607,
                                      -0.019866078767932702,
                                      -0.015248941295772145,
                                      0.020480690262803695,
                                      0.02737677703091019,
                                      -0.016652959083222105,
                                      -0.11442365705990722}

//--------------------------------------------------------------------
// Functions
//--------------------------------------------------------------------

func DeSquealFirInit(f* DeSquealFir) {
    for i := 0; i < len(deSquealFilterTaps); i++ {
        f.History[i] = 0
    }

    f.LastIndex = 0
}

func DeSquealFirPut(f* DeSquealFir, input float32) {
    f.History[f.LastIndex] = input
    f.LastIndex++
    if f.LastIndex == len(deSquealFilterTaps) {
        f.LastIndex = 0
    }
}

func DeSquealFirGet(f* DeSquealFir) float32 {
    var acc float32 = 0
    var index int = f.LastIndex

    for i := 0; i < len(deSquealFilterTaps); i++ {
        if index != 0 {
            index = index - 1
        } else {
            index = len(deSquealFilterTaps) - 1
        }
       acc += f.History[index] * deSquealFilterTaps[i]
    }

  return acc
}

/* End Of File */
