/* Deemphasis filtering for the Internet of Chuffs server,
 * approximating to the inverse of CCITT J17
 * This code based on C code generated by the wonderful http://t-filter.appspot.com 
 */

package main

/*

FIR filter designed with
 http://t-filter.appspot.com

sampling frequency: 16000 Hz

* 0 Hz - 2000 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.5108114330532016 dB

* 3000 Hz - 4000 Hz
  gain = 0.9
  desired ripple = 5 dB
  actual ripple = 3.237093155052075 dB

* 5000 Hz - 7000 Hz
  gain = 0.5
  desired ripple = 5 dB
  actual ripple = 3.5108114330532016 dB

* 7850 Hz - 8000 Hz
  gain = 0
  desired attenuation = -20 dB
  actual attenuation = -21.45902385508648 dB

*/

//--------------------------------------------------------------------
// Types
//--------------------------------------------------------------------

const FIR_TAP_NUM int = 11

type Fir struct {
  History    [FIR_TAP_NUM]float32
  LastIndex  int
}

//--------------------------------------------------------------------
// Constants
//--------------------------------------------------------------------

//--------------------------------------------------------------------
// Variables
//--------------------------------------------------------------------

var filterTaps = [...]float32{ 0.10023736088945266,
                              -0.005871968635765682,
                              -0.006033248294353573,
                              -0.026636261716912468,
                               0.18695603980905007,
                               0.7020874365822828,
                               0.18695603980905007,
                              -0.026636261716912468,
                              -0.006033248294353573,
                              -0.005871968635765682,
                               0.10023736088945266}

//--------------------------------------------------------------------
// Functions
//--------------------------------------------------------------------

func FirInit(f* Fir) {
    for i := 0; i < len(filterTaps); i++ {
        f.History[i] = 0
    }

    f.LastIndex = 0
}

func FirPut(f* Fir, input float32) {
    f.History[f.LastIndex] = input
    f.LastIndex++
    if f.LastIndex == len(filterTaps) {
        f.LastIndex = 0
    }
}

func FirGet(f* Fir) float32 {
    var acc float32 = 0
    var index int = f.LastIndex

    for i := 0; i < len(filterTaps); i++ {
        if index != 0 {
            index = index - 1
        } else {
            index = len(filterTaps) - 1
        }
       acc += f.History[index] * filterTaps[i]
    }

  return acc
}

/* End Of File */
