/* Deemphasis filtering for the Internet of Chuffs server,
 * approximating to the inverse of CCITT J17
 * This code based on C code generated by the wonderful http://t-filter.appspot.com 
 */

package main

/*

FIR filter designed with
 http://t-filter.appspot.com

sampling frequency: 16000 Hz

* 0 Hz - 50 Hz
  gain = 50
  desired ripple = 50 dB
  actual ripple = 10.81932029406067 dB

* 150 Hz - 1000 Hz
  gain = 10
  desired ripple = 10 dB
  actual ripple = 9.051819918084604 dB

* 1500 Hz - 3500 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.9718847345536457 dB

* 4000 Hz - 8000 Hz
  gain = 1
  desired ripple = 5 dB
  actual ripple = 3.9718847345536457 dB

*/

//--------------------------------------------------------------------
// Types
//--------------------------------------------------------------------

const FIR_TAP_NUM int = 17

type Fir struct {
  History    [FIR_TAP_NUM]float32
  LastIndex  int
}

//--------------------------------------------------------------------
// Constants
//--------------------------------------------------------------------

//--------------------------------------------------------------------
// Variables
//--------------------------------------------------------------------

var filterTaps = [...]float32{0.22743865399053123,
                              0.3067750113860418,
                              0.47463722418828264,
                              0.6646312531223915,
                              0.8603437142687377,
                              1.0420151414166308,
                              1.1897087282228245,
                              1.2863277963220066,
                              2.3199792614553156,
                              1.2863277963220066,
                              1.1897087282228245,
                              1.0420151414166308,
                              0.8603437142687377,
                              0.6646312531223915,
                              0.47463722418828264,
                              0.3067750113860418,
                              0.22743865399053123}

//--------------------------------------------------------------------
// Functions
//--------------------------------------------------------------------

func FirInit(f* Fir) {
    for i := 0; i < len(filterTaps); i++ {
        f.History[i] = 0
    }

    f.LastIndex = 0
}

func FirPut(f* Fir, input float32) {
    f.History[f.LastIndex] = input
    f.LastIndex++
    if f.LastIndex == len(filterTaps) {
        f.LastIndex = 0
    }
}

func FirGet(f* Fir) float32 {
    var acc float32 = 0
    var index int = f.LastIndex

    for i := 0; i < len(filterTaps); i++ {
        if index != 0 {
            index = index - 1
        } else {
            index = len(filterTaps) - 1
        }
       acc += f.History[index] * filterTaps[i]
    }

  return acc
}

/* End Of File */
